-- Run this in the EXISTING Supabase project.
-- These are new standalone tables for the Sinhala Subtitle Bot.
-- Do not delete or modify your existing Cine Universe tables.

create table if not exists public.cine_subtitles (
  id bigint generated by default as identity primary key,
  unique_key text not null unique,
  tmdb_id bigint,
  title text not null,
  normalized_title text not null,
  year integer,
  season integer,
  episode integer,
  language text not null default 'Sinhala',
  format text not null default 'SRT',
  telegram_channel_id text not null,
  telegram_message_id bigint not null,
  telegram_file_id text not null,
  telegram_file_unique_id text,
  file_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cine_subtitles_lookup_idx
  on public.cine_subtitles (tmdb_id, year, season, episode, language);

create index if not exists cine_subtitles_title_idx
  on public.cine_subtitles (normalized_title);

create index if not exists cine_subtitles_file_idx
  on public.cine_subtitles (telegram_file_unique_id);

create table if not exists public.cine_subtitle_notifications (
  id bigint generated by default as identity primary key,
  unique_key text not null unique,
  user_id text not null,
  tmdb_id bigint,
  title text not null,
  year integer,
  season integer,
  episode integer,
  language text not null default 'Sinhala',
  notified boolean not null default false,
  created_at timestamptz not null default now(),
  notified_at timestamptz
);

create index if not exists cine_subtitle_notifications_lookup_idx
  on public.cine_subtitle_notifications (tmdb_id, title, year, season, episode, language);


-- Persistent storage for Notify Me button payloads.
-- Telegram callback_data is limited to 64 bytes, so the button stores only this row id.
create table if not exists public.cine_subtitle_notification_requests (
  id bigint generated by default as identity primary key,
  user_id text not null,
  title text not null,
  tmdb_id bigint,
  year integer,
  season integer,
  episode integer,
  language text not null default 'Sinhala',
  created_at timestamptz not null default now()
);

create index if not exists cine_subtitle_notification_requests_user_idx
on public.cine_subtitle_notification_requests (user_id, created_at);
